// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: branches.proto

package com.haberdashervcs.common.protobuf;

public final class BranchesProto {
  private BranchesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BranchEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BranchEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * This is redundant since the name is in the row key, but for now I still want it as a field.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * This is redundant since the name is in the row key, but for now I still want it as a field.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int64 headCommitId = 2;</code>
     * @return The headCommitId.
     */
    long getHeadCommitId();

    /**
     * <pre>
     * Branching-off point from main.
     * </pre>
     *
     * <code>int64 baseCommitId = 3;</code>
     * @return The baseCommitId.
     */
    long getBaseCommitId();
  }
  /**
   * Protobuf type {@code BranchEntry}
   */
  public static final class BranchEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BranchEntry)
      BranchEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BranchEntry.newBuilder() to construct.
    private BranchEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BranchEntry() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BranchEntry();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BranchEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              headCommitId_ = input.readInt64();
              break;
            }
            case 24: {

              baseCommitId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haberdashervcs.common.protobuf.BranchesProto.internal_static_BranchEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haberdashervcs.common.protobuf.BranchesProto.internal_static_BranchEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry.class, com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * This is redundant since the name is in the row key, but for now I still want it as a field.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * This is redundant since the name is in the row key, but for now I still want it as a field.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADCOMMITID_FIELD_NUMBER = 2;
    private long headCommitId_;
    /**
     * <code>int64 headCommitId = 2;</code>
     * @return The headCommitId.
     */
    @java.lang.Override
    public long getHeadCommitId() {
      return headCommitId_;
    }

    public static final int BASECOMMITID_FIELD_NUMBER = 3;
    private long baseCommitId_;
    /**
     * <pre>
     * Branching-off point from main.
     * </pre>
     *
     * <code>int64 baseCommitId = 3;</code>
     * @return The baseCommitId.
     */
    @java.lang.Override
    public long getBaseCommitId() {
      return baseCommitId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (headCommitId_ != 0L) {
        output.writeInt64(2, headCommitId_);
      }
      if (baseCommitId_ != 0L) {
        output.writeInt64(3, baseCommitId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (headCommitId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, headCommitId_);
      }
      if (baseCommitId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, baseCommitId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry)) {
        return super.equals(obj);
      }
      com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry other = (com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getHeadCommitId()
          != other.getHeadCommitId()) return false;
      if (getBaseCommitId()
          != other.getBaseCommitId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HEADCOMMITID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeadCommitId());
      hash = (37 * hash) + BASECOMMITID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBaseCommitId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BranchEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BranchEntry)
        com.haberdashervcs.common.protobuf.BranchesProto.BranchEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.haberdashervcs.common.protobuf.BranchesProto.internal_static_BranchEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.haberdashervcs.common.protobuf.BranchesProto.internal_static_BranchEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry.class, com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry.Builder.class);
      }

      // Construct using com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        headCommitId_ = 0L;

        baseCommitId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.haberdashervcs.common.protobuf.BranchesProto.internal_static_BranchEntry_descriptor;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry getDefaultInstanceForType() {
        return com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry.getDefaultInstance();
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry build() {
        com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry buildPartial() {
        com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry result = new com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry(this);
        result.name_ = name_;
        result.headCommitId_ = headCommitId_;
        result.baseCommitId_ = baseCommitId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry) {
          return mergeFrom((com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry other) {
        if (other == com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getHeadCommitId() != 0L) {
          setHeadCommitId(other.getHeadCommitId());
        }
        if (other.getBaseCommitId() != 0L) {
          setBaseCommitId(other.getBaseCommitId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * This is redundant since the name is in the row key, but for now I still want it as a field.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * This is redundant since the name is in the row key, but for now I still want it as a field.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * This is redundant since the name is in the row key, but for now I still want it as a field.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This is redundant since the name is in the row key, but for now I still want it as a field.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This is redundant since the name is in the row key, but for now I still want it as a field.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long headCommitId_ ;
      /**
       * <code>int64 headCommitId = 2;</code>
       * @return The headCommitId.
       */
      @java.lang.Override
      public long getHeadCommitId() {
        return headCommitId_;
      }
      /**
       * <code>int64 headCommitId = 2;</code>
       * @param value The headCommitId to set.
       * @return This builder for chaining.
       */
      public Builder setHeadCommitId(long value) {
        
        headCommitId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 headCommitId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadCommitId() {
        
        headCommitId_ = 0L;
        onChanged();
        return this;
      }

      private long baseCommitId_ ;
      /**
       * <pre>
       * Branching-off point from main.
       * </pre>
       *
       * <code>int64 baseCommitId = 3;</code>
       * @return The baseCommitId.
       */
      @java.lang.Override
      public long getBaseCommitId() {
        return baseCommitId_;
      }
      /**
       * <pre>
       * Branching-off point from main.
       * </pre>
       *
       * <code>int64 baseCommitId = 3;</code>
       * @param value The baseCommitId to set.
       * @return This builder for chaining.
       */
      public Builder setBaseCommitId(long value) {
        
        baseCommitId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Branching-off point from main.
       * </pre>
       *
       * <code>int64 baseCommitId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseCommitId() {
        
        baseCommitId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BranchEntry)
    }

    // @@protoc_insertion_point(class_scope:BranchEntry)
    private static final com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry();
    }

    public static com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BranchEntry>
        PARSER = new com.google.protobuf.AbstractParser<BranchEntry>() {
      @java.lang.Override
      public BranchEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BranchEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BranchEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BranchEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.haberdashervcs.common.protobuf.BranchesProto.BranchEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BranchEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BranchEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016branches.proto\"G\n\013BranchEntry\022\014\n\004name\030" +
      "\001 \001(\t\022\024\n\014headCommitId\030\002 \001(\003\022\024\n\014baseCommi" +
      "tId\030\003 \001(\003B5\n\"com.haberdashervcs.common.p" +
      "rotobufB\rBranchesProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BranchEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BranchEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BranchEntry_descriptor,
        new java.lang.String[] { "Name", "HeadCommitId", "BaseCommitId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
