// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files.proto

package com.haberdashervcs.common.protobuf;

public final class FilesProto {
  private FilesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * TODO?: For diffs, should we have code parse this as a proto message of one kind or another, depending on the diff
     *     type? That way, we can have different diff settings or metadata along with the diff contents.
     * </pre>
     *
     * <code>bytes contents = 2;</code>
     * @return The contents.
     */
    com.google.protobuf.ByteString getContents();

    /**
     * <code>.FileEntry.ContentsType contentsType = 3;</code>
     * @return The enum numeric value on the wire for contentsType.
     */
    int getContentsTypeValue();
    /**
     * <code>.FileEntry.ContentsType contentsType = 3;</code>
     * @return The contentsType.
     */
    com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType getContentsType();

    /**
     * <code>.FileEntry.StorageType storageType = 4;</code>
     * @return The enum numeric value on the wire for storageType.
     */
    int getStorageTypeValue();
    /**
     * <code>.FileEntry.StorageType storageType = 4;</code>
     * @return The storageType.
     */
    com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType getStorageType();

    /**
     * <code>string diffBaseEntryId = 5;</code>
     * @return The diffBaseEntryId.
     */
    java.lang.String getDiffBaseEntryId();
    /**
     * <code>string diffBaseEntryId = 5;</code>
     * @return The bytes for diffBaseEntryId.
     */
    com.google.protobuf.ByteString
        getDiffBaseEntryIdBytes();
  }
  /**
   * Protobuf type {@code FileEntry}
   */
  public static final class FileEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileEntry)
      FileEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileEntry.newBuilder() to construct.
    private FileEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileEntry() {
      id_ = "";
      contents_ = com.google.protobuf.ByteString.EMPTY;
      contentsType_ = 0;
      storageType_ = 0;
      diffBaseEntryId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileEntry();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {

              contents_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              contentsType_ = rawValue;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              storageType_ = rawValue;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              diffBaseEntryId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haberdashervcs.common.protobuf.FilesProto.internal_static_FileEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haberdashervcs.common.protobuf.FilesProto.internal_static_FileEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haberdashervcs.common.protobuf.FilesProto.FileEntry.class, com.haberdashervcs.common.protobuf.FilesProto.FileEntry.Builder.class);
    }

    /**
     * Protobuf enum {@code FileEntry.ContentsType}
     */
    public enum ContentsType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FULL = 0;</code>
       */
      FULL(0),
      /**
       * <pre>
       * Diffs parsed by GitDeltaDiffer
       * </pre>
       *
       * <code>DIFF_GIT = 1;</code>
       */
      DIFF_GIT(1),
      /**
       * <pre>
       * Binary diff with bsdiff
       * </pre>
       *
       * <code>DIFF_BS = 2;</code>
       */
      DIFF_BS(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FULL = 0;</code>
       */
      public static final int FULL_VALUE = 0;
      /**
       * <pre>
       * Diffs parsed by GitDeltaDiffer
       * </pre>
       *
       * <code>DIFF_GIT = 1;</code>
       */
      public static final int DIFF_GIT_VALUE = 1;
      /**
       * <pre>
       * Binary diff with bsdiff
       * </pre>
       *
       * <code>DIFF_BS = 2;</code>
       */
      public static final int DIFF_BS_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ContentsType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ContentsType forNumber(int value) {
        switch (value) {
          case 0: return FULL;
          case 1: return DIFF_GIT;
          case 2: return DIFF_BS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ContentsType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ContentsType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ContentsType>() {
              public ContentsType findValueByNumber(int number) {
                return ContentsType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.haberdashervcs.common.protobuf.FilesProto.FileEntry.getDescriptor().getEnumTypes().get(0);
      }

      private static final ContentsType[] VALUES = values();

      public static ContentsType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ContentsType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:FileEntry.ContentsType)
    }

    /**
     * Protobuf enum {@code FileEntry.StorageType}
     */
    public enum StorageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DATASTORE = 0;</code>
       */
      DATASTORE(0),
      /**
       * <code>LARGE_FILE_STORE = 1;</code>
       */
      LARGE_FILE_STORE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DATASTORE = 0;</code>
       */
      public static final int DATASTORE_VALUE = 0;
      /**
       * <code>LARGE_FILE_STORE = 1;</code>
       */
      public static final int LARGE_FILE_STORE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static StorageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static StorageType forNumber(int value) {
        switch (value) {
          case 0: return DATASTORE;
          case 1: return LARGE_FILE_STORE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StorageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          StorageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StorageType>() {
              public StorageType findValueByNumber(int number) {
                return StorageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.haberdashervcs.common.protobuf.FilesProto.FileEntry.getDescriptor().getEnumTypes().get(1);
      }

      private static final StorageType[] VALUES = values();

      public static StorageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private StorageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:FileEntry.StorageType)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString contents_;
    /**
     * <pre>
     * TODO?: For diffs, should we have code parse this as a proto message of one kind or another, depending on the diff
     *     type? That way, we can have different diff settings or metadata along with the diff contents.
     * </pre>
     *
     * <code>bytes contents = 2;</code>
     * @return The contents.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContents() {
      return contents_;
    }

    public static final int CONTENTSTYPE_FIELD_NUMBER = 3;
    private int contentsType_;
    /**
     * <code>.FileEntry.ContentsType contentsType = 3;</code>
     * @return The enum numeric value on the wire for contentsType.
     */
    @java.lang.Override public int getContentsTypeValue() {
      return contentsType_;
    }
    /**
     * <code>.FileEntry.ContentsType contentsType = 3;</code>
     * @return The contentsType.
     */
    @java.lang.Override public com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType getContentsType() {
      @SuppressWarnings("deprecation")
      com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType result = com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType.valueOf(contentsType_);
      return result == null ? com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType.UNRECOGNIZED : result;
    }

    public static final int STORAGETYPE_FIELD_NUMBER = 4;
    private int storageType_;
    /**
     * <code>.FileEntry.StorageType storageType = 4;</code>
     * @return The enum numeric value on the wire for storageType.
     */
    @java.lang.Override public int getStorageTypeValue() {
      return storageType_;
    }
    /**
     * <code>.FileEntry.StorageType storageType = 4;</code>
     * @return The storageType.
     */
    @java.lang.Override public com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType getStorageType() {
      @SuppressWarnings("deprecation")
      com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType result = com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType.valueOf(storageType_);
      return result == null ? com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType.UNRECOGNIZED : result;
    }

    public static final int DIFFBASEENTRYID_FIELD_NUMBER = 5;
    private volatile java.lang.Object diffBaseEntryId_;
    /**
     * <code>string diffBaseEntryId = 5;</code>
     * @return The diffBaseEntryId.
     */
    @java.lang.Override
    public java.lang.String getDiffBaseEntryId() {
      java.lang.Object ref = diffBaseEntryId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        diffBaseEntryId_ = s;
        return s;
      }
    }
    /**
     * <code>string diffBaseEntryId = 5;</code>
     * @return The bytes for diffBaseEntryId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDiffBaseEntryIdBytes() {
      java.lang.Object ref = diffBaseEntryId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        diffBaseEntryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!contents_.isEmpty()) {
        output.writeBytes(2, contents_);
      }
      if (contentsType_ != com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType.FULL.getNumber()) {
        output.writeEnum(3, contentsType_);
      }
      if (storageType_ != com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType.DATASTORE.getNumber()) {
        output.writeEnum(4, storageType_);
      }
      if (!getDiffBaseEntryIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, diffBaseEntryId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!contents_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, contents_);
      }
      if (contentsType_ != com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType.FULL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, contentsType_);
      }
      if (storageType_ != com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType.DATASTORE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, storageType_);
      }
      if (!getDiffBaseEntryIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, diffBaseEntryId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.haberdashervcs.common.protobuf.FilesProto.FileEntry)) {
        return super.equals(obj);
      }
      com.haberdashervcs.common.protobuf.FilesProto.FileEntry other = (com.haberdashervcs.common.protobuf.FilesProto.FileEntry) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getContents()
          .equals(other.getContents())) return false;
      if (contentsType_ != other.contentsType_) return false;
      if (storageType_ != other.storageType_) return false;
      if (!getDiffBaseEntryId()
          .equals(other.getDiffBaseEntryId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CONTENTS_FIELD_NUMBER;
      hash = (53 * hash) + getContents().hashCode();
      hash = (37 * hash) + CONTENTSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + contentsType_;
      hash = (37 * hash) + STORAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + storageType_;
      hash = (37 * hash) + DIFFBASEENTRYID_FIELD_NUMBER;
      hash = (53 * hash) + getDiffBaseEntryId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.haberdashervcs.common.protobuf.FilesProto.FileEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileEntry)
        com.haberdashervcs.common.protobuf.FilesProto.FileEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.haberdashervcs.common.protobuf.FilesProto.internal_static_FileEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.haberdashervcs.common.protobuf.FilesProto.internal_static_FileEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.haberdashervcs.common.protobuf.FilesProto.FileEntry.class, com.haberdashervcs.common.protobuf.FilesProto.FileEntry.Builder.class);
      }

      // Construct using com.haberdashervcs.common.protobuf.FilesProto.FileEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        contents_ = com.google.protobuf.ByteString.EMPTY;

        contentsType_ = 0;

        storageType_ = 0;

        diffBaseEntryId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.haberdashervcs.common.protobuf.FilesProto.internal_static_FileEntry_descriptor;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.FilesProto.FileEntry getDefaultInstanceForType() {
        return com.haberdashervcs.common.protobuf.FilesProto.FileEntry.getDefaultInstance();
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.FilesProto.FileEntry build() {
        com.haberdashervcs.common.protobuf.FilesProto.FileEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.FilesProto.FileEntry buildPartial() {
        com.haberdashervcs.common.protobuf.FilesProto.FileEntry result = new com.haberdashervcs.common.protobuf.FilesProto.FileEntry(this);
        result.id_ = id_;
        result.contents_ = contents_;
        result.contentsType_ = contentsType_;
        result.storageType_ = storageType_;
        result.diffBaseEntryId_ = diffBaseEntryId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.haberdashervcs.common.protobuf.FilesProto.FileEntry) {
          return mergeFrom((com.haberdashervcs.common.protobuf.FilesProto.FileEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.haberdashervcs.common.protobuf.FilesProto.FileEntry other) {
        if (other == com.haberdashervcs.common.protobuf.FilesProto.FileEntry.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getContents() != com.google.protobuf.ByteString.EMPTY) {
          setContents(other.getContents());
        }
        if (other.contentsType_ != 0) {
          setContentsTypeValue(other.getContentsTypeValue());
        }
        if (other.storageType_ != 0) {
          setStorageTypeValue(other.getStorageTypeValue());
        }
        if (!other.getDiffBaseEntryId().isEmpty()) {
          diffBaseEntryId_ = other.diffBaseEntryId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.haberdashervcs.common.protobuf.FilesProto.FileEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.haberdashervcs.common.protobuf.FilesProto.FileEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contents_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * TODO?: For diffs, should we have code parse this as a proto message of one kind or another, depending on the diff
       *     type? That way, we can have different diff settings or metadata along with the diff contents.
       * </pre>
       *
       * <code>bytes contents = 2;</code>
       * @return The contents.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getContents() {
        return contents_;
      }
      /**
       * <pre>
       * TODO?: For diffs, should we have code parse this as a proto message of one kind or another, depending on the diff
       *     type? That way, we can have different diff settings or metadata along with the diff contents.
       * </pre>
       *
       * <code>bytes contents = 2;</code>
       * @param value The contents to set.
       * @return This builder for chaining.
       */
      public Builder setContents(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contents_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * TODO?: For diffs, should we have code parse this as a proto message of one kind or another, depending on the diff
       *     type? That way, we can have different diff settings or metadata along with the diff contents.
       * </pre>
       *
       * <code>bytes contents = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContents() {
        
        contents_ = getDefaultInstance().getContents();
        onChanged();
        return this;
      }

      private int contentsType_ = 0;
      /**
       * <code>.FileEntry.ContentsType contentsType = 3;</code>
       * @return The enum numeric value on the wire for contentsType.
       */
      @java.lang.Override public int getContentsTypeValue() {
        return contentsType_;
      }
      /**
       * <code>.FileEntry.ContentsType contentsType = 3;</code>
       * @param value The enum numeric value on the wire for contentsType to set.
       * @return This builder for chaining.
       */
      public Builder setContentsTypeValue(int value) {
        
        contentsType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.FileEntry.ContentsType contentsType = 3;</code>
       * @return The contentsType.
       */
      @java.lang.Override
      public com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType getContentsType() {
        @SuppressWarnings("deprecation")
        com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType result = com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType.valueOf(contentsType_);
        return result == null ? com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType.UNRECOGNIZED : result;
      }
      /**
       * <code>.FileEntry.ContentsType contentsType = 3;</code>
       * @param value The contentsType to set.
       * @return This builder for chaining.
       */
      public Builder setContentsType(com.haberdashervcs.common.protobuf.FilesProto.FileEntry.ContentsType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        contentsType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.FileEntry.ContentsType contentsType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContentsType() {
        
        contentsType_ = 0;
        onChanged();
        return this;
      }

      private int storageType_ = 0;
      /**
       * <code>.FileEntry.StorageType storageType = 4;</code>
       * @return The enum numeric value on the wire for storageType.
       */
      @java.lang.Override public int getStorageTypeValue() {
        return storageType_;
      }
      /**
       * <code>.FileEntry.StorageType storageType = 4;</code>
       * @param value The enum numeric value on the wire for storageType to set.
       * @return This builder for chaining.
       */
      public Builder setStorageTypeValue(int value) {
        
        storageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.FileEntry.StorageType storageType = 4;</code>
       * @return The storageType.
       */
      @java.lang.Override
      public com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType getStorageType() {
        @SuppressWarnings("deprecation")
        com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType result = com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType.valueOf(storageType_);
        return result == null ? com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.FileEntry.StorageType storageType = 4;</code>
       * @param value The storageType to set.
       * @return This builder for chaining.
       */
      public Builder setStorageType(com.haberdashervcs.common.protobuf.FilesProto.FileEntry.StorageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        storageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.FileEntry.StorageType storageType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStorageType() {
        
        storageType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object diffBaseEntryId_ = "";
      /**
       * <code>string diffBaseEntryId = 5;</code>
       * @return The diffBaseEntryId.
       */
      public java.lang.String getDiffBaseEntryId() {
        java.lang.Object ref = diffBaseEntryId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          diffBaseEntryId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string diffBaseEntryId = 5;</code>
       * @return The bytes for diffBaseEntryId.
       */
      public com.google.protobuf.ByteString
          getDiffBaseEntryIdBytes() {
        java.lang.Object ref = diffBaseEntryId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          diffBaseEntryId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string diffBaseEntryId = 5;</code>
       * @param value The diffBaseEntryId to set.
       * @return This builder for chaining.
       */
      public Builder setDiffBaseEntryId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        diffBaseEntryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string diffBaseEntryId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiffBaseEntryId() {
        
        diffBaseEntryId_ = getDefaultInstance().getDiffBaseEntryId();
        onChanged();
        return this;
      }
      /**
       * <code>string diffBaseEntryId = 5;</code>
       * @param value The bytes for diffBaseEntryId to set.
       * @return This builder for chaining.
       */
      public Builder setDiffBaseEntryIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        diffBaseEntryId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileEntry)
    }

    // @@protoc_insertion_point(class_scope:FileEntry)
    private static final com.haberdashervcs.common.protobuf.FilesProto.FileEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.haberdashervcs.common.protobuf.FilesProto.FileEntry();
    }

    public static com.haberdashervcs.common.protobuf.FilesProto.FileEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileEntry>
        PARSER = new com.google.protobuf.AbstractParser<FileEntry>() {
      @java.lang.Override
      public FileEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.haberdashervcs.common.protobuf.FilesProto.FileEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013files.proto\"\207\002\n\tFileEntry\022\n\n\002id\030\001 \001(\t\022" +
      "\020\n\010contents\030\002 \001(\014\022-\n\014contentsType\030\003 \001(\0162" +
      "\027.FileEntry.ContentsType\022+\n\013storageType\030" +
      "\004 \001(\0162\026.FileEntry.StorageType\022\027\n\017diffBas" +
      "eEntryId\030\005 \001(\t\"3\n\014ContentsType\022\010\n\004FULL\020\000" +
      "\022\014\n\010DIFF_GIT\020\001\022\013\n\007DIFF_BS\020\002\"2\n\013StorageTy" +
      "pe\022\r\n\tDATASTORE\020\000\022\024\n\020LARGE_FILE_STORE\020\001B" +
      "2\n\"com.haberdashervcs.common.protobufB\nF" +
      "ilesProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FileEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileEntry_descriptor,
        new java.lang.String[] { "Id", "Contents", "ContentsType", "StorageType", "DiffBaseEntryId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
