// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: localdb.proto

package com.haberdashervcs.common.protobuf;

public final class LocalDbProto {
  private LocalDbProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocalBranchStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LocalBranchState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string branchName = 1;</code>
     * @return The branchName.
     */
    java.lang.String getBranchName();
    /**
     * <code>string branchName = 1;</code>
     * @return The bytes for branchName.
     */
    com.google.protobuf.ByteString
        getBranchNameBytes();

    /**
     * <code>int64 baseCommitId = 2;</code>
     * @return The baseCommitId.
     */
    long getBaseCommitId();

    /**
     * <code>int64 headCommitId = 3;</code>
     * @return The headCommitId.
     */
    long getHeadCommitId();

    /**
     * <code>int64 currentlySyncedCommitId = 4;</code>
     * @return The currentlySyncedCommitId.
     */
    long getCurrentlySyncedCommitId();
  }
  /**
   * Protobuf type {@code LocalBranchState}
   */
  public static final class LocalBranchState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LocalBranchState)
      LocalBranchStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocalBranchState.newBuilder() to construct.
    private LocalBranchState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocalBranchState() {
      branchName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LocalBranchState();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocalBranchState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              branchName_ = s;
              break;
            }
            case 16: {

              baseCommitId_ = input.readInt64();
              break;
            }
            case 24: {

              headCommitId_ = input.readInt64();
              break;
            }
            case 32: {

              currentlySyncedCommitId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haberdashervcs.common.protobuf.LocalDbProto.internal_static_LocalBranchState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haberdashervcs.common.protobuf.LocalDbProto.internal_static_LocalBranchState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState.class, com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState.Builder.class);
    }

    public static final int BRANCHNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object branchName_;
    /**
     * <code>string branchName = 1;</code>
     * @return The branchName.
     */
    @java.lang.Override
    public java.lang.String getBranchName() {
      java.lang.Object ref = branchName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        branchName_ = s;
        return s;
      }
    }
    /**
     * <code>string branchName = 1;</code>
     * @return The bytes for branchName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBranchNameBytes() {
      java.lang.Object ref = branchName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        branchName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASECOMMITID_FIELD_NUMBER = 2;
    private long baseCommitId_;
    /**
     * <code>int64 baseCommitId = 2;</code>
     * @return The baseCommitId.
     */
    @java.lang.Override
    public long getBaseCommitId() {
      return baseCommitId_;
    }

    public static final int HEADCOMMITID_FIELD_NUMBER = 3;
    private long headCommitId_;
    /**
     * <code>int64 headCommitId = 3;</code>
     * @return The headCommitId.
     */
    @java.lang.Override
    public long getHeadCommitId() {
      return headCommitId_;
    }

    public static final int CURRENTLYSYNCEDCOMMITID_FIELD_NUMBER = 4;
    private long currentlySyncedCommitId_;
    /**
     * <code>int64 currentlySyncedCommitId = 4;</code>
     * @return The currentlySyncedCommitId.
     */
    @java.lang.Override
    public long getCurrentlySyncedCommitId() {
      return currentlySyncedCommitId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBranchNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, branchName_);
      }
      if (baseCommitId_ != 0L) {
        output.writeInt64(2, baseCommitId_);
      }
      if (headCommitId_ != 0L) {
        output.writeInt64(3, headCommitId_);
      }
      if (currentlySyncedCommitId_ != 0L) {
        output.writeInt64(4, currentlySyncedCommitId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBranchNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, branchName_);
      }
      if (baseCommitId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, baseCommitId_);
      }
      if (headCommitId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, headCommitId_);
      }
      if (currentlySyncedCommitId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, currentlySyncedCommitId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState)) {
        return super.equals(obj);
      }
      com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState other = (com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState) obj;

      if (!getBranchName()
          .equals(other.getBranchName())) return false;
      if (getBaseCommitId()
          != other.getBaseCommitId()) return false;
      if (getHeadCommitId()
          != other.getHeadCommitId()) return false;
      if (getCurrentlySyncedCommitId()
          != other.getCurrentlySyncedCommitId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BRANCHNAME_FIELD_NUMBER;
      hash = (53 * hash) + getBranchName().hashCode();
      hash = (37 * hash) + BASECOMMITID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBaseCommitId());
      hash = (37 * hash) + HEADCOMMITID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeadCommitId());
      hash = (37 * hash) + CURRENTLYSYNCEDCOMMITID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrentlySyncedCommitId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LocalBranchState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LocalBranchState)
        com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.haberdashervcs.common.protobuf.LocalDbProto.internal_static_LocalBranchState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.haberdashervcs.common.protobuf.LocalDbProto.internal_static_LocalBranchState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState.class, com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState.Builder.class);
      }

      // Construct using com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        branchName_ = "";

        baseCommitId_ = 0L;

        headCommitId_ = 0L;

        currentlySyncedCommitId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.haberdashervcs.common.protobuf.LocalDbProto.internal_static_LocalBranchState_descriptor;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState getDefaultInstanceForType() {
        return com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState.getDefaultInstance();
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState build() {
        com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState buildPartial() {
        com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState result = new com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState(this);
        result.branchName_ = branchName_;
        result.baseCommitId_ = baseCommitId_;
        result.headCommitId_ = headCommitId_;
        result.currentlySyncedCommitId_ = currentlySyncedCommitId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState) {
          return mergeFrom((com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState other) {
        if (other == com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState.getDefaultInstance()) return this;
        if (!other.getBranchName().isEmpty()) {
          branchName_ = other.branchName_;
          onChanged();
        }
        if (other.getBaseCommitId() != 0L) {
          setBaseCommitId(other.getBaseCommitId());
        }
        if (other.getHeadCommitId() != 0L) {
          setHeadCommitId(other.getHeadCommitId());
        }
        if (other.getCurrentlySyncedCommitId() != 0L) {
          setCurrentlySyncedCommitId(other.getCurrentlySyncedCommitId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object branchName_ = "";
      /**
       * <code>string branchName = 1;</code>
       * @return The branchName.
       */
      public java.lang.String getBranchName() {
        java.lang.Object ref = branchName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          branchName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string branchName = 1;</code>
       * @return The bytes for branchName.
       */
      public com.google.protobuf.ByteString
          getBranchNameBytes() {
        java.lang.Object ref = branchName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          branchName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string branchName = 1;</code>
       * @param value The branchName to set.
       * @return This builder for chaining.
       */
      public Builder setBranchName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        branchName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string branchName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBranchName() {
        
        branchName_ = getDefaultInstance().getBranchName();
        onChanged();
        return this;
      }
      /**
       * <code>string branchName = 1;</code>
       * @param value The bytes for branchName to set.
       * @return This builder for chaining.
       */
      public Builder setBranchNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        branchName_ = value;
        onChanged();
        return this;
      }

      private long baseCommitId_ ;
      /**
       * <code>int64 baseCommitId = 2;</code>
       * @return The baseCommitId.
       */
      @java.lang.Override
      public long getBaseCommitId() {
        return baseCommitId_;
      }
      /**
       * <code>int64 baseCommitId = 2;</code>
       * @param value The baseCommitId to set.
       * @return This builder for chaining.
       */
      public Builder setBaseCommitId(long value) {
        
        baseCommitId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 baseCommitId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseCommitId() {
        
        baseCommitId_ = 0L;
        onChanged();
        return this;
      }

      private long headCommitId_ ;
      /**
       * <code>int64 headCommitId = 3;</code>
       * @return The headCommitId.
       */
      @java.lang.Override
      public long getHeadCommitId() {
        return headCommitId_;
      }
      /**
       * <code>int64 headCommitId = 3;</code>
       * @param value The headCommitId to set.
       * @return This builder for chaining.
       */
      public Builder setHeadCommitId(long value) {
        
        headCommitId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 headCommitId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadCommitId() {
        
        headCommitId_ = 0L;
        onChanged();
        return this;
      }

      private long currentlySyncedCommitId_ ;
      /**
       * <code>int64 currentlySyncedCommitId = 4;</code>
       * @return The currentlySyncedCommitId.
       */
      @java.lang.Override
      public long getCurrentlySyncedCommitId() {
        return currentlySyncedCommitId_;
      }
      /**
       * <code>int64 currentlySyncedCommitId = 4;</code>
       * @param value The currentlySyncedCommitId to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentlySyncedCommitId(long value) {
        
        currentlySyncedCommitId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 currentlySyncedCommitId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentlySyncedCommitId() {
        
        currentlySyncedCommitId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LocalBranchState)
    }

    // @@protoc_insertion_point(class_scope:LocalBranchState)
    private static final com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState();
    }

    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocalBranchState>
        PARSER = new com.google.protobuf.AbstractParser<LocalBranchState>() {
      @java.lang.Override
      public LocalBranchState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocalBranchState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocalBranchState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocalBranchState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.haberdashervcs.common.protobuf.LocalDbProto.LocalBranchState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocalRepoStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LocalRepoState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.LocalRepoState.RepoState state = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <code>.LocalRepoState.RepoState state = 1;</code>
     * @return The state.
     */
    com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState getState();

    /**
     * <pre>
     * In the form "main:N"
     * </pre>
     *
     * <code>string rebaseCommitBeingIntegrated = 2;</code>
     * @return The rebaseCommitBeingIntegrated.
     */
    java.lang.String getRebaseCommitBeingIntegrated();
    /**
     * <pre>
     * In the form "main:N"
     * </pre>
     *
     * <code>string rebaseCommitBeingIntegrated = 2;</code>
     * @return The bytes for rebaseCommitBeingIntegrated.
     */
    com.google.protobuf.ByteString
        getRebaseCommitBeingIntegratedBytes();
  }
  /**
   * Protobuf type {@code LocalRepoState}
   */
  public static final class LocalRepoState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LocalRepoState)
      LocalRepoStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocalRepoState.newBuilder() to construct.
    private LocalRepoState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocalRepoState() {
      state_ = 0;
      rebaseCommitBeingIntegrated_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LocalRepoState();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocalRepoState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              rebaseCommitBeingIntegrated_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haberdashervcs.common.protobuf.LocalDbProto.internal_static_LocalRepoState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haberdashervcs.common.protobuf.LocalDbProto.internal_static_LocalRepoState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.class, com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.Builder.class);
    }

    /**
     * Protobuf enum {@code LocalRepoState.RepoState}
     */
    public enum RepoState
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NORMAL = 0;</code>
       */
      NORMAL(0),
      /**
       * <code>REBASE_IN_PROGRESS = 1;</code>
       */
      REBASE_IN_PROGRESS(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NORMAL = 0;</code>
       */
      public static final int NORMAL_VALUE = 0;
      /**
       * <code>REBASE_IN_PROGRESS = 1;</code>
       */
      public static final int REBASE_IN_PROGRESS_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RepoState valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static RepoState forNumber(int value) {
        switch (value) {
          case 0: return NORMAL;
          case 1: return REBASE_IN_PROGRESS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RepoState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RepoState> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RepoState>() {
              public RepoState findValueByNumber(int number) {
                return RepoState.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.getDescriptor().getEnumTypes().get(0);
      }

      private static final RepoState[] VALUES = values();

      public static RepoState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RepoState(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:LocalRepoState.RepoState)
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <code>.LocalRepoState.RepoState state = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.LocalRepoState.RepoState state = 1;</code>
     * @return The state.
     */
    @java.lang.Override public com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState getState() {
      @SuppressWarnings("deprecation")
      com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState result = com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState.valueOf(state_);
      return result == null ? com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState.UNRECOGNIZED : result;
    }

    public static final int REBASECOMMITBEINGINTEGRATED_FIELD_NUMBER = 2;
    private volatile java.lang.Object rebaseCommitBeingIntegrated_;
    /**
     * <pre>
     * In the form "main:N"
     * </pre>
     *
     * <code>string rebaseCommitBeingIntegrated = 2;</code>
     * @return The rebaseCommitBeingIntegrated.
     */
    @java.lang.Override
    public java.lang.String getRebaseCommitBeingIntegrated() {
      java.lang.Object ref = rebaseCommitBeingIntegrated_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rebaseCommitBeingIntegrated_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * In the form "main:N"
     * </pre>
     *
     * <code>string rebaseCommitBeingIntegrated = 2;</code>
     * @return The bytes for rebaseCommitBeingIntegrated.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRebaseCommitBeingIntegratedBytes() {
      java.lang.Object ref = rebaseCommitBeingIntegrated_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rebaseCommitBeingIntegrated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState.NORMAL.getNumber()) {
        output.writeEnum(1, state_);
      }
      if (!getRebaseCommitBeingIntegratedBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rebaseCommitBeingIntegrated_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState.NORMAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      if (!getRebaseCommitBeingIntegratedBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rebaseCommitBeingIntegrated_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState)) {
        return super.equals(obj);
      }
      com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState other = (com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState) obj;

      if (state_ != other.state_) return false;
      if (!getRebaseCommitBeingIntegrated()
          .equals(other.getRebaseCommitBeingIntegrated())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (37 * hash) + REBASECOMMITBEINGINTEGRATED_FIELD_NUMBER;
      hash = (53 * hash) + getRebaseCommitBeingIntegrated().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LocalRepoState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LocalRepoState)
        com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.haberdashervcs.common.protobuf.LocalDbProto.internal_static_LocalRepoState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.haberdashervcs.common.protobuf.LocalDbProto.internal_static_LocalRepoState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.class, com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.Builder.class);
      }

      // Construct using com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        state_ = 0;

        rebaseCommitBeingIntegrated_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.haberdashervcs.common.protobuf.LocalDbProto.internal_static_LocalRepoState_descriptor;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState getDefaultInstanceForType() {
        return com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.getDefaultInstance();
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState build() {
        com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState buildPartial() {
        com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState result = new com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState(this);
        result.state_ = state_;
        result.rebaseCommitBeingIntegrated_ = rebaseCommitBeingIntegrated_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState) {
          return mergeFrom((com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState other) {
        if (other == com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.getDefaultInstance()) return this;
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (!other.getRebaseCommitBeingIntegrated().isEmpty()) {
          rebaseCommitBeingIntegrated_ = other.rebaseCommitBeingIntegrated_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.LocalRepoState.RepoState state = 1;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <code>.LocalRepoState.RepoState state = 1;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.LocalRepoState.RepoState state = 1;</code>
       * @return The state.
       */
      @java.lang.Override
      public com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState getState() {
        @SuppressWarnings("deprecation")
        com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState result = com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState.valueOf(state_);
        return result == null ? com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState.UNRECOGNIZED : result;
      }
      /**
       * <code>.LocalRepoState.RepoState state = 1;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState.RepoState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.LocalRepoState.RepoState state = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object rebaseCommitBeingIntegrated_ = "";
      /**
       * <pre>
       * In the form "main:N"
       * </pre>
       *
       * <code>string rebaseCommitBeingIntegrated = 2;</code>
       * @return The rebaseCommitBeingIntegrated.
       */
      public java.lang.String getRebaseCommitBeingIntegrated() {
        java.lang.Object ref = rebaseCommitBeingIntegrated_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rebaseCommitBeingIntegrated_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * In the form "main:N"
       * </pre>
       *
       * <code>string rebaseCommitBeingIntegrated = 2;</code>
       * @return The bytes for rebaseCommitBeingIntegrated.
       */
      public com.google.protobuf.ByteString
          getRebaseCommitBeingIntegratedBytes() {
        java.lang.Object ref = rebaseCommitBeingIntegrated_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rebaseCommitBeingIntegrated_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * In the form "main:N"
       * </pre>
       *
       * <code>string rebaseCommitBeingIntegrated = 2;</code>
       * @param value The rebaseCommitBeingIntegrated to set.
       * @return This builder for chaining.
       */
      public Builder setRebaseCommitBeingIntegrated(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rebaseCommitBeingIntegrated_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * In the form "main:N"
       * </pre>
       *
       * <code>string rebaseCommitBeingIntegrated = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRebaseCommitBeingIntegrated() {
        
        rebaseCommitBeingIntegrated_ = getDefaultInstance().getRebaseCommitBeingIntegrated();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * In the form "main:N"
       * </pre>
       *
       * <code>string rebaseCommitBeingIntegrated = 2;</code>
       * @param value The bytes for rebaseCommitBeingIntegrated to set.
       * @return This builder for chaining.
       */
      public Builder setRebaseCommitBeingIntegratedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rebaseCommitBeingIntegrated_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LocalRepoState)
    }

    // @@protoc_insertion_point(class_scope:LocalRepoState)
    private static final com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState();
    }

    public static com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocalRepoState>
        PARSER = new com.google.protobuf.AbstractParser<LocalRepoState>() {
      @java.lang.Override
      public LocalRepoState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocalRepoState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocalRepoState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocalRepoState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.haberdashervcs.common.protobuf.LocalDbProto.LocalRepoState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocalBranchState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocalBranchState_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocalRepoState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocalRepoState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rlocaldb.proto\"s\n\020LocalBranchState\022\022\n\nb" +
      "ranchName\030\001 \001(\t\022\024\n\014baseCommitId\030\002 \001(\003\022\024\n" +
      "\014headCommitId\030\003 \001(\003\022\037\n\027currentlySyncedCo" +
      "mmitId\030\004 \001(\003\"\220\001\n\016LocalRepoState\022(\n\005state" +
      "\030\001 \001(\0162\031.LocalRepoState.RepoState\022#\n\033reb" +
      "aseCommitBeingIntegrated\030\002 \001(\t\"/\n\tRepoSt" +
      "ate\022\n\n\006NORMAL\020\000\022\026\n\022REBASE_IN_PROGRESS\020\001B" +
      "4\n\"com.haberdashervcs.common.protobufB\014L" +
      "ocalDbProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LocalBranchState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LocalBranchState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocalBranchState_descriptor,
        new java.lang.String[] { "BranchName", "BaseCommitId", "HeadCommitId", "CurrentlySyncedCommitId", });
    internal_static_LocalRepoState_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LocalRepoState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocalRepoState_descriptor,
        new java.lang.String[] { "State", "RebaseCommitBeingIntegrated", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
