// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: merges.proto

package com.haberdashervcs.common.protobuf;

public final class MergesProto {
  private MergesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MergeLockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MergeLock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The id field here is technically redundant since the id is in the row key, but I like having it here anyway for
     *     now.
     * TODO: revisit this? ^
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <pre>
     * The id field here is technically redundant since the id is in the row key, but I like having it here anyway for
     *     now.
     * TODO: revisit this? ^
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string branchName = 2;</code>
     * @return The branchName.
     */
    java.lang.String getBranchName();
    /**
     * <code>string branchName = 2;</code>
     * @return The bytes for branchName.
     */
    com.google.protobuf.ByteString
        getBranchNameBytes();

    /**
     * <code>.MergeLock.State state = 3;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <code>.MergeLock.State state = 3;</code>
     * @return The state.
     */
    com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State getState();

    /**
     * <code>int64 timestampMillis = 4;</code>
     * @return The timestampMillis.
     */
    long getTimestampMillis();
  }
  /**
   * Protobuf type {@code MergeLock}
   */
  public static final class MergeLock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MergeLock)
      MergeLockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MergeLock.newBuilder() to construct.
    private MergeLock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MergeLock() {
      id_ = "";
      branchName_ = "";
      state_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MergeLock();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MergeLock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              branchName_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 32: {

              timestampMillis_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haberdashervcs.common.protobuf.MergesProto.internal_static_MergeLock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haberdashervcs.common.protobuf.MergesProto.internal_static_MergeLock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haberdashervcs.common.protobuf.MergesProto.MergeLock.class, com.haberdashervcs.common.protobuf.MergesProto.MergeLock.Builder.class);
    }

    /**
     * Protobuf enum {@code MergeLock.State}
     */
    public enum State
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>IN_PROGRESS = 0;</code>
       */
      IN_PROGRESS(0),
      /**
       * <code>COMPLETED = 1;</code>
       */
      COMPLETED(1),
      /**
       * <code>FAILED = 2;</code>
       */
      FAILED(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>IN_PROGRESS = 0;</code>
       */
      public static final int IN_PROGRESS_VALUE = 0;
      /**
       * <code>COMPLETED = 1;</code>
       */
      public static final int COMPLETED_VALUE = 1;
      /**
       * <code>FAILED = 2;</code>
       */
      public static final int FAILED_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static State valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static State forNumber(int value) {
        switch (value) {
          case 0: return IN_PROGRESS;
          case 1: return COMPLETED;
          case 2: return FAILED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          State> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.haberdashervcs.common.protobuf.MergesProto.MergeLock.getDescriptor().getEnumTypes().get(0);
      }

      private static final State[] VALUES = values();

      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private State(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MergeLock.State)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     * The id field here is technically redundant since the id is in the row key, but I like having it here anyway for
     *     now.
     * TODO: revisit this? ^
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The id field here is technically redundant since the id is in the row key, but I like having it here anyway for
     *     now.
     * TODO: revisit this? ^
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRANCHNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object branchName_;
    /**
     * <code>string branchName = 2;</code>
     * @return The branchName.
     */
    @java.lang.Override
    public java.lang.String getBranchName() {
      java.lang.Object ref = branchName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        branchName_ = s;
        return s;
      }
    }
    /**
     * <code>string branchName = 2;</code>
     * @return The bytes for branchName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBranchNameBytes() {
      java.lang.Object ref = branchName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        branchName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 3;
    private int state_;
    /**
     * <code>.MergeLock.State state = 3;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.MergeLock.State state = 3;</code>
     * @return The state.
     */
    @java.lang.Override public com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State getState() {
      @SuppressWarnings("deprecation")
      com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State result = com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State.valueOf(state_);
      return result == null ? com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State.UNRECOGNIZED : result;
    }

    public static final int TIMESTAMPMILLIS_FIELD_NUMBER = 4;
    private long timestampMillis_;
    /**
     * <code>int64 timestampMillis = 4;</code>
     * @return The timestampMillis.
     */
    @java.lang.Override
    public long getTimestampMillis() {
      return timestampMillis_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getBranchNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, branchName_);
      }
      if (state_ != com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State.IN_PROGRESS.getNumber()) {
        output.writeEnum(3, state_);
      }
      if (timestampMillis_ != 0L) {
        output.writeInt64(4, timestampMillis_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getBranchNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, branchName_);
      }
      if (state_ != com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State.IN_PROGRESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, state_);
      }
      if (timestampMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestampMillis_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.haberdashervcs.common.protobuf.MergesProto.MergeLock)) {
        return super.equals(obj);
      }
      com.haberdashervcs.common.protobuf.MergesProto.MergeLock other = (com.haberdashervcs.common.protobuf.MergesProto.MergeLock) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getBranchName()
          .equals(other.getBranchName())) return false;
      if (state_ != other.state_) return false;
      if (getTimestampMillis()
          != other.getTimestampMillis()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + BRANCHNAME_FIELD_NUMBER;
      hash = (53 * hash) + getBranchName().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (37 * hash) + TIMESTAMPMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestampMillis());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.haberdashervcs.common.protobuf.MergesProto.MergeLock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MergeLock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MergeLock)
        com.haberdashervcs.common.protobuf.MergesProto.MergeLockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.haberdashervcs.common.protobuf.MergesProto.internal_static_MergeLock_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.haberdashervcs.common.protobuf.MergesProto.internal_static_MergeLock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.haberdashervcs.common.protobuf.MergesProto.MergeLock.class, com.haberdashervcs.common.protobuf.MergesProto.MergeLock.Builder.class);
      }

      // Construct using com.haberdashervcs.common.protobuf.MergesProto.MergeLock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        branchName_ = "";

        state_ = 0;

        timestampMillis_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.haberdashervcs.common.protobuf.MergesProto.internal_static_MergeLock_descriptor;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.MergesProto.MergeLock getDefaultInstanceForType() {
        return com.haberdashervcs.common.protobuf.MergesProto.MergeLock.getDefaultInstance();
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.MergesProto.MergeLock build() {
        com.haberdashervcs.common.protobuf.MergesProto.MergeLock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.MergesProto.MergeLock buildPartial() {
        com.haberdashervcs.common.protobuf.MergesProto.MergeLock result = new com.haberdashervcs.common.protobuf.MergesProto.MergeLock(this);
        result.id_ = id_;
        result.branchName_ = branchName_;
        result.state_ = state_;
        result.timestampMillis_ = timestampMillis_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.haberdashervcs.common.protobuf.MergesProto.MergeLock) {
          return mergeFrom((com.haberdashervcs.common.protobuf.MergesProto.MergeLock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.haberdashervcs.common.protobuf.MergesProto.MergeLock other) {
        if (other == com.haberdashervcs.common.protobuf.MergesProto.MergeLock.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getBranchName().isEmpty()) {
          branchName_ = other.branchName_;
          onChanged();
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (other.getTimestampMillis() != 0L) {
          setTimestampMillis(other.getTimestampMillis());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.haberdashervcs.common.protobuf.MergesProto.MergeLock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.haberdashervcs.common.protobuf.MergesProto.MergeLock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * The id field here is technically redundant since the id is in the row key, but I like having it here anyway for
       *     now.
       * TODO: revisit this? ^
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The id field here is technically redundant since the id is in the row key, but I like having it here anyway for
       *     now.
       * TODO: revisit this? ^
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The id field here is technically redundant since the id is in the row key, but I like having it here anyway for
       *     now.
       * TODO: revisit this? ^
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The id field here is technically redundant since the id is in the row key, but I like having it here anyway for
       *     now.
       * TODO: revisit this? ^
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The id field here is technically redundant since the id is in the row key, but I like having it here anyway for
       *     now.
       * TODO: revisit this? ^
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object branchName_ = "";
      /**
       * <code>string branchName = 2;</code>
       * @return The branchName.
       */
      public java.lang.String getBranchName() {
        java.lang.Object ref = branchName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          branchName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string branchName = 2;</code>
       * @return The bytes for branchName.
       */
      public com.google.protobuf.ByteString
          getBranchNameBytes() {
        java.lang.Object ref = branchName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          branchName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string branchName = 2;</code>
       * @param value The branchName to set.
       * @return This builder for chaining.
       */
      public Builder setBranchName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        branchName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string branchName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBranchName() {
        
        branchName_ = getDefaultInstance().getBranchName();
        onChanged();
        return this;
      }
      /**
       * <code>string branchName = 2;</code>
       * @param value The bytes for branchName to set.
       * @return This builder for chaining.
       */
      public Builder setBranchNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        branchName_ = value;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.MergeLock.State state = 3;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <code>.MergeLock.State state = 3;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MergeLock.State state = 3;</code>
       * @return The state.
       */
      @java.lang.Override
      public com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State getState() {
        @SuppressWarnings("deprecation")
        com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State result = com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State.valueOf(state_);
        return result == null ? com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State.UNRECOGNIZED : result;
      }
      /**
       * <code>.MergeLock.State state = 3;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(com.haberdashervcs.common.protobuf.MergesProto.MergeLock.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MergeLock.State state = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private long timestampMillis_ ;
      /**
       * <code>int64 timestampMillis = 4;</code>
       * @return The timestampMillis.
       */
      @java.lang.Override
      public long getTimestampMillis() {
        return timestampMillis_;
      }
      /**
       * <code>int64 timestampMillis = 4;</code>
       * @param value The timestampMillis to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampMillis(long value) {
        
        timestampMillis_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestampMillis = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampMillis() {
        
        timestampMillis_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MergeLock)
    }

    // @@protoc_insertion_point(class_scope:MergeLock)
    private static final com.haberdashervcs.common.protobuf.MergesProto.MergeLock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.haberdashervcs.common.protobuf.MergesProto.MergeLock();
    }

    public static com.haberdashervcs.common.protobuf.MergesProto.MergeLock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MergeLock>
        PARSER = new com.google.protobuf.AbstractParser<MergeLock>() {
      @java.lang.Override
      public MergeLock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MergeLock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MergeLock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MergeLock> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.haberdashervcs.common.protobuf.MergesProto.MergeLock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MergeLock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MergeLock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014merges.proto\"\232\001\n\tMergeLock\022\n\n\002id\030\001 \001(\t" +
      "\022\022\n\nbranchName\030\002 \001(\t\022\037\n\005state\030\003 \001(\0162\020.Me" +
      "rgeLock.State\022\027\n\017timestampMillis\030\004 \001(\003\"3" +
      "\n\005State\022\017\n\013IN_PROGRESS\020\000\022\r\n\tCOMPLETED\020\001\022" +
      "\n\n\006FAILED\020\002B3\n\"com.haberdashervcs.common" +
      ".protobufB\013MergesProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MergeLock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MergeLock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MergeLock_descriptor,
        new java.lang.String[] { "Id", "BranchName", "State", "TimestampMillis", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
